/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  horizen_eon: [
    {
      type: 'category',
      label: 'Introduction - What is EON',
      items: [
        {
          type: 'doc',
          id: 'docs/horizen_eon/introduction_what_is_eon/introduction',
        },
        {
          type: 'doc',
          id: 'docs/horizen_eon/introduction_what_is_eon/Inside_EON',
        },
        {
          type: 'doc',
          id: 'docs/horizen_eon/introduction_what_is_eon/environments',
        },
      ],
    },
    {
      type: 'category',
      label: 'Exploring the Network',
      items: [
        {
          type: 'doc',
          id: 'docs/horizen_eon/connect/get_a_wallet',
        },
        {
          type: 'doc',
          id: 'docs/horizen_eon/connect/connect_your_wallet',
        },
        {
          type: 'doc',
          id: 'docs/horizen_eon/connect/get_tzen_from_the_faucet',
        },
      ],
    },
  ],
  governance: [
    {
      type: 'category',
      label: 'Governance',
      items: [
        {
          type: 'doc',
          id: 'docs/governance/test/introduction',
        },
      ],
    },
  ],
  // horizen_eon: {
  //   'Introduction - What is EON': [
  //     'docs/horizen_eon/introduction_what_is_eon/introduction',
  //     'docs/horizen_eon/introduction_what_is_eon/Inside_EON',
  //     'docs/horizen_eon/introduction_what_is_eon/environments',
  //   ],
  //   'Exploring the Network': [
  //     'docs/horizen_eon/connect/get_a_wallet',
  //     'docs/horizen_eon/connect/connect_your_wallet',
  //     'docs/horizen_eon/connect/get_tzen_from_the_faucet',
  //     'docs/horizen_eon/connect/eon_block_explorer',
  //   ],
  //   'Develop and Deploy - Smart Contracts': [
  //     'docs/horizen_eon/develop_and_deploy_smart_contracts/remix',
  //     'docs/horizen_eon/develop_and_deploy_smart_contracts/hardhat',
  //     'docs/horizen_eon/develop_and_deploy_smart_contracts/truffle',
  //     'docs/horizen_eon/develop_and_deploy_smart_contracts/local_build_and_deploy',
  //     'docs/horizen_eon/develop_and_deploy_smart_contracts/verying_a_smart_contract',
  //   ],
  //   'Tutorials': [
  //     'docs/horizen_eon/tutorials/thirdweb',
  //     'docs/horizen_eon/tutorials/todolist',
  //   ],
  //   'Get Help': [
  //     'docs/horizen_eon/get_help/terminology',
  //     'docs/horizen_eon/get_help/troubleshooting',
  //     'docs/horizen_eon/get_help/disclaimer',
  //   ],
  //   'Security Guides': [
  //     'docs/horizen_eon/security_guides/security_user',
  //   ],
  // },
  // governance: {
  //   'Governance': [
  //     'docs/governance/test/introduction',
  //   ],
  // },
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
